# Generated by Django 6.0.2 on 2026-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='current_location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(max_length=250),
        ),
    ]
