# Generated by Django 6.0.2 on 2026-02-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='longitude',
        ),
    ]
